### ISSUE TITLE
in function histGeneM(), there should be 'colors = makePalette()'

### ISSUE THREAD

**Issue by PengchengYu0328** [lrylaarsdam/amethyst#2]
In `visualize.R`/`histGeneM()` function, the line `colors = makeAmethystPalette(),`seems should be changed to `colors = makePalette(),`

**Comment by lrylaarsdam** [comment]
Thanks for bringing this to my attention, and sorry for not addressing it earlier. You are correct. The old function name (makeAmethystPalette) is no longer in referenced.
