### ISSUE TITLE
Install issues seemingly related to clusterCompare

### ISSUE THREAD

**Issue by davidnoe-l** [lrylaarsdam/amethyst#9]
Hi, 

I wanted to give your amazing package a go but I have trouble installing it even after making sure that all dependencies are installed. 

> devtools::install_github("lrylaarsdam/amethyst")
Downloading GitHub repo lrylaarsdam/amethyst@HEAD
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/Rtmp0sDAM0/remotes2e725d711aaf01/lrylaarsdam-amethyst-2854bea/DESCRIPTION’ (631ms)
─  preparing ‘amethyst’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘amethyst_0.0.0.9000.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into ‘/homes2/davidh/R/x86_64-pc-linux-gnu-library/4.4’
(as ‘lib’ is unspecified)
* installing *source* package ‘amethyst’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Warning: replacing previous import ‘GenomicRanges::reduce’ by ‘purrr::reduce’ when loading ‘amethyst’
** help
*** installing help indices
  converting help for package ‘amethyst’
    finding HTML links ... done
    addAnnot                                html  
    addCellInfo                             html  
    addDoubletScores                        html  
    addMatrixMeans                          html  
    addMetadata                             html  
    aggregateMatrix                         html  
    buildDoubletModel                       html  
    calcSmoothedWindows                     html  
    clusterCompare                          html  
    clusterLabelTransfer                    html  
    collapseDMR                             html  
    combineObject                           html  
    createObject                            html  
    createScaleObject                       html  
    dimEstimate                             html  
    dimFeature                              html  
    dimM                                    html  
    dotGeneM                                html  
    dotM                                    html  
    extractAttributes                       html  
    fetchMarkers                            html  
    filterDMR                               html  
    findClusterMarkers                      html  
    findRanges                              html  
    getGeneM                                html  
    heatMap                                 html  
    histGeneM                               html  
    histograM                               html  
    impute                                  html  
    indexChr                                html  
    indexGenes                              html  
    makeAmethystPalette                     html  
    makeClusterTracks                       html  
    makeDoubletObject                       html  
    makeFuzzyGeneWindows                    html  
    makePalette                             html  
    makeRef                                 html  
    makeSlidingWindows                      html  
    makeWindows                             html  
    markerHeatmap                           html  
    noAxes                                  html  
    predictDoubletScores                    html  
    regressCovBias                          html  
    roundAny                                html  
    runCluster                              html  
    runIrlba                                html  
    runTsne                                 html  
    runUmap                                 html  
    sampleComp                              html  
    subsetObject                            html  
    testDMR                                 html  
    testPalette                             html  
    tileGeneM                               html  
    transferLabelsNN                        html  
    umapFeature                             html  
    umapGeneM                               html  
    violinM                                 html  
    vlnGeneM                                html  
** building package indices
** testing if installed package can be loaded from temporary location
Warning: replacing previous import ‘GenomicRanges::reduce’ by ‘purrr::reduce’ when loading ‘amethyst’
Error: package or namespace load failed for ‘amethyst’ in namespaceExport(ns, exports):
 undefined exports: clusterCompare
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/homes2/davidh/R/x86_64-pc-linux-gnu-library/4.4/amethyst’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp0sDAM0/file2e725d716e153b/amethyst_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by lrylaarsdam** [comment]
Hi David, 

Thanks so much for bringing this to my attention. You are correct - a deprecated function remained in the namespace file after a recent update, resulting in the error. It should be fixed now. Please let me know if you have any further trouble with the installation.

Best,
Lauren
